### PR TITLE
- Replace several instances of "Any" with "ExprValues".

### PR DESCRIPTION
**Pull request by TorkelE**
Added `const ExprValues = Union{Expr,Symbol,Number}` and replaced it in all appropriate places. Should not be any `Any` left now.

### CODE REVIEW

**Comment by isaacsas** [comment]
Looks good, I only have two minor comments:
1. Maybe put the definition of `Exprvalues` in the DiffEqBiological.jl file before the includes?
2. I wonder if we should define `Exprvalues` to be
```
const ExprValues = Union{Expr,Symbol,Float64,Int}
```
since `Number` is an abstract type? I have no idea if that might give a performance gain from being more concretely typed.

**Comment by TorkelE** [comment]
Sounds good, should it be `Union{Expr,Symbol,Float64,Int}` or `Union{Expr,Symbol,Float64,Int64}`?

**Comment by isaacsas** [comment]
I’d use int since it is the native integer type on each platform.

**Comment by isaacsas** [comment]
It looks like the Julia docs indicate up to four types should still be efficient. So I think we should be ok. 

You could look at the reported test timings before and after the change in type to make sure we don’t see any big slowdown.

**Comment by TorkelE** [comment]
Good, changes are in.

**Comment by isaacsas** [comment]
I’ll plan to merge when tests finish.

**Pull request merged**
