### PR TITLE
Increase HomotopyContinuation compat.

### LINKED ISSUE #177: Unsatisfiable requirements - HomotopyContinuation
The CI tests currently fail with an unsatisfiable version restriction on HomotopyContinuation. 

Failing HomotopyContinuation:
https://travis-ci.org/JuliaDiffEq/DiffEqBiological.jl/jobs/618522172

It seems that we are restricting ourselves to HomotopyContinuation v0.7 when the newest version is v1.2.1. This old version of HomotopyContinuation is not specified as compatible with the newer versions of DynamicPolynomials that we have as an explicit requirement.

### PR DESCRIPTION
**Pull request by korsbo**
Trying to fix #177

### CODE REVIEW

**Comment by korsbo** [comment]
The error on Julia 1.1 seems unrelated to HomotopyContinuation:
```
ERROR: Unsatisfiable requirements detected for package FunctionWrappers [069b7b12]:
 FunctionWrappers [069b7b12] log:
 ├─possible versions are: 1.0.0 or uninstalled
 ├─restricted by compatibility requirements with DiffEqBase [2b5f629d] to versions: 1.0.0
 │ └─DiffEqBase [2b5f629d] log:
 │   ├─possible versions are: [3.13.2-3.13.3, 4.0.0-4.0.1, 4.1.0, 4.2.0, 4.3.0-4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 4.10.0-4.10.1, 4.11.0-4.11.1, 4.12.0, 4.13.0, 4.14.0-4.14.1, 4.15.0, 4.16.0, 4.17.0, 4.18.0, 4.19.0, 4.20.0-4.20.3, 4.21.0, 4.21.2-4.21.3, 4.22.0-4.22.2, 4.23.0, 4.23.2-4.23.4, 4.24.0-4.24.3, 4.25.0-4.25.1, 4.26.0-4.26.3, 4.27.0-4.27.1, 4.28.0-4.28.1, 4.29.0-4.29.2, 4.30.0-4.30.2, 4.31.0-4.31.2, 4.32.0, 5.0.0-5.0.1, 5.1.0, 5.2.0-5.2.3, 5.3.0-5.3.2, 5.4.0-5.4.1, 5.5.0-5.5.2, 5.6.0-5.6.4, 5.7.0, 5.8.0-5.8.1, 5.9.0, 5.10.0-5.10.3, 5.11.0-5.11.1, 5.12.0, 5.13.0, 5.14.0-5.14.2, 5.15.0, 5.16.0-5.16.5, 5.17.0-5.17.1, 5.18.0, 5.19.0, 5.20.0-5.20.1, 6.0.0, 6.1.0, 6.2.0-6.2.4, 6.3.0-6.3.6, 6.4.0-6.4.2, 6.5.0] or uninstalled
 │   └─restricted to versions 6.0.0-6 by an explicit requirement, leaving only versions [6.0.0, 6.1.0, 6.2.0-6.2.4, 6.3.0-6.3.6, 6.4.0-6.4.2, 6.5.0]
 └─restricted by compatibility requirements with Compat [34da2185] to versions: uninstalled — no versions left
   └─Compat [34da2185] log:
     ├─possible versions are: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0] or uninstalled
     └─restricted to versions 3.0.0-3 by an explicit requirement, leaving only versions 3.0.0
```

**Comment by korsbo** [comment]
FunctionWrappers.jl specifies Compat.jl v1 while DiffEqBase needs Compat.jl v2 or v3.

**Comment by ChrisRackauckas** [comment]
Yeah, and it's probably compatible. Someone just needs to make a Project.toml for FunctionWrappers.jl

**Comment by korsbo** [comment]
https://github.com/yuyichao/FunctionWrappers.jl/issues/9

**Pull request closed without merging**
