### PR TITLE
Fix deprecation warning on Julia v0.6 and later

### PR DESCRIPTION
**Pull request by ScottPJones**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
No, just use Compat. It's simpler than this weird stuff.

**Comment by ScottPJones** [comment]
OK, will do.

**Comment by ChrisRackauckas** [comment]
Fixed the spelling error.

**Comment by ScottPJones** [comment]
D*mn!  Sorry about the spelling error! I'd tested everything before, but was falling asleep when I did the "simple" fix of changing to use Compat. Ugh!

**Pull request merged**
