### PR TITLE
add DiscreteProblem overload for reaction_networks

### PR DESCRIPTION
**Pull request by isaacsas**
Added an overload so that we can do:
```
dprob = DiscreteProblem(rn, u0, tspan, p)
```
This allows plots of jump simulations to actually get the species syms in the legend. For example, the repressilator as a jump process:
syms

### CODE REVIEW

**Comment by isaacsas** [comment]
This relies on DiffEqBase [187](https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/187), so probably won’t pass tests till a new release of it is tagged.

**Comment by isaacsas** [comment]
Looks like the registry still hasn't picked up the DiffEqBase 5.1... I'll bump this once it updates so tests re-run...

**Comment by isaacsas** [comment]
It needs the `DiscreteFunction` that takes `syms`, doesn't that require 5.1 or greater? I thought that was why Travis was failing (at least why it was failing prior to the whole registry issue today).

**Comment by ChrisRackauckas** [comment]
Oh yes it does need the bound. My bad.

**Pull request merged**
