### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by matbesancon**
Fix broken html links

### CODE REVIEW

**Comment by isaacsas** [comment]
Thanks!

**Comment by ChrisRackauckas** [comment]
We should regenerate the Latexify tests

**Comment by isaacsas** [comment]
Yeah, I think @korsbo was planning on doing that, otherwise I can try to look into it later this week if I get a chance.

**Comment by ChrisRackauckas** [comment]
`Latexify.@generate_test latexify([1, 2, 3], [4, 5, 6]; env=:mdtable)` is an example. It just spits out the code to copy paste. So it's not too difficult, just needs someone to get the free time!

**Pull request merged**
